debug = False

comment = ""

[train]
model_name = UCSGNet_lr{}_latent_sz{}_csglayer{}_outshape{}_batch_size{}_data_size{}_dim{}

# Whether to load a pretrained model or not
preload_model = False

# path to the pre-trained model
pretrain_model_path = "trained_models/temp1.pth"

#Dimension of CSG shape
num_dim = 3

# Number of epochs to run during training
num_epochs = 500

# batch size, based on the GPU memory
batch_size = 16

# final output size of encoder
latent_sz = 256

# Learning rate
lr = 1e-4

# Optimizer: sgd or adam
optim = adam

# Number of shapes per type
num_shape_type = 64

# beta1, 2of adam
beta1 = 0.5
beta2 = 0.99

#Determines the points sampled from data 64, 32, 16
data_size = 32

# number of sdf sample per batch
points_per_sample_in_batch = 1024

#Number of output shapes per layer
out_shape_layer = 12

#Thresholding value for weights. If weight > threshold, 1 else 0
threshold = 0.5

#Planes later combined or False to use Circle, Square
use_planes = False

#Number of csg_layers
num_csg_layer = 6

#Number of worker in dataloader
worker = 4

#Dataloader path
path = "data/hdf5/"